var GlobalTime = 0,
MarkTime = 0,
Speed = 5,
CurrentScreen = 'levelStart',
GameOver = false,
Pause = false,
SetNewGame = true,
Hero,
Background,
Asteroids_Number = 20,
Asteroids = [],
CurrentAsteroid = undefined,
Cargo = 0,
CargoTotal = 0,
CargoGoal = 0,
InCentral = false,
Hits = []
;